version: '3.2'

services:

  mariadb:
    image: mariadb
    # inherited from docker-compose.yml
  webserver:
    # overrides the image used from docker-compose.yml
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        VITE_VERSION: "${VITE_VERSION}"
    # inherited from docker-compose.yml
    
  matomo:
    image: matomo
    # inherited from docker-compose.yml
