version: '3.2'

services:

  mariadb:
    image: mariadb
    # inherited from docker-compose.yml
  pacnexus:
    # overrides the image used from docker-compose.yml
    build: 
      context: .
      dockerfile: pacnexus.Dockerfile
      args:
        VITE_VERSION: "${VITE_VERSION}"
    environment:
      PACSTALL_LOG_LEVEL: "debug"
    # inherited from docker-compose.yml
  pacsight:
    # overrides the image used from docker-compose.yml
    build: 
      context: .
      dockerfile: pacsight.Dockerfile
      args:
        VITE_VERSION: "${VITE_VERSION}"
    environment:
      PACSTALL_LOG_LEVEL: "debug"
    # inherited from docker-compose.yml
    
  matomo:
    image: matomo
    # inherited from docker-compose.yml
