#------------------------------------------------------------------------------#
#--------------------         Server Configuration         --------------------#
#------------------------------------------------------------------------------#

#---------------------------------   Manual   ---------------------------------#
#------------------------------------------------------------------------------#

#                 #
# --- Globals --- #
#                 #

# If true, the server starts a file server located at `tcp_server.public_dir`
# `production`: = `bool`

#                                          #
# --- Pacstall Programs ( Repository ) --- #
#                                          #

# Path to the `pacstall-programs` local repository
# `pacstall_programs.path`             = `string`

# Temporary dir path to store scripts. If the dir doesn't exist, it gets created
# `pacstall_programs.tmp_dir`          = `string`

#  How often to pull git commits. Time in milliseconds
# `pacstall_programs.update_interval`  = `int`

#  Maximum number of open files during the package scanning
# `pacstall_programs.max_open_files`   = `int`

#                    #
# --- TCP Server --- #
#                    #

# What port to listen on
# `tcp_server.port`        = `int`

# Directory containing all public html files
# `tcp_server.public_dir`  = `string` 

#                       #
# --- Feature Flags --- #
#                       #

# Syntax for the pacstall cli
# `feature_flags.old_syntax` = `bool`

# `feature_flags.package_details_page.last_updated`     = `bool`
# `feature_flags.package_details_page.votes`            = `bool`
# `feature_flags.package_details_page.popularity`       = `bool`
# `feature_flags.package_details_page.install_protocol` = `bool`
# `feature_flags.package_details_page.comments`         = `bool`



#------------------------------------------------------------------------------#


production = false

[pacstall_programs]
path            = "../../pacstall-programs"
tmp_dir         = "./tmp"
update_interval = 900000
max_open_files  = 100

[tcp_server]
port        = 3300
public_dir  = "./public"

[feature_flags]
old_syntax = true

[feature_flags.package_details_page]
last_updated     = false
votes            = false
popularity       = false
install_protocol = false
comments         = false

#------------------------------------------------------------------------------#