openapi: 3.0.0
servers:
  - url: '/api'
    description: Production
info:
  description: This document represents the specification of Pacstall's API
  version: "1.0.0"
  title: Pacstall Webserver API
  contact:
    email: pacstall@protonmail.com
  license:
    name: GNU Affero General Public License
    url: 'https://www.gnu.org/licenses/agpl-3.0.en.html'
tags:
  - name: packages
    description: Endpoints to find and filter packages
paths:
  /packages:
    get:
      tags:
        - packages
      summary: searches packages
      parameters:
        - in: query
          name: page
          description: page number
          required: false
          schema:
            default: 0
            type: integer
            minimum: 0
        - in: query
          name: pageSize
          description: page size
          required: false
          schema:
            type: integer
            default: 50
            minimum: 0
        - in: query
          name: filter
          description: search terms
          required: false
          schema:
            type: string
            default: ""
      responses:
        '200':
          description: 'page of packages'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PackagePage'
                
  /packages/{name}:
    get:
      tags:
        - packages
      summary: package details
      parameters:
        - in: path
          name: name
          description: 'package name'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 'package details'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Package'
  
  /repology:
    get:
      tags:
        - repology
      summary: all packages in a Repology friendly format
      responses:
        '200':
          description: all packages
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RepologyPackage'

components:
  schemas:
    PackagePage:
      type: object
      properties:
        page:
          type: integer
        size:
          type: integer
          example: 50
        sort:
          type: string
          enum: ['asc', 'desc']
        sortBy:
          type: string
          example: "name"
        filter:
          type: string
          example: "chrome"
        filterBy:
          type: string
          enum: ['name', 'maintainer']
        total:
          type: integer
          example: 12832
        lastPage:
          type: integer
          example: 2123
        data:
          type: array
          items:
            $ref: '#/components/schemas/Package'
          
    Package:
      type: object
      properties:
        name:
          type: string
          example: 'nodejs-lts-deb'
        prettyName:
          type: string
          example: 'Node.js LTS'
        version:
          type: string
          example: '16.0.1'
        latestVersion:
          type: string
          example: '16.1.1'
          description: 'This might be "Unknown" if repology filters are not present'
        packageName:
          type: string
          example: 'nodejs-lts'
          description: 'Some pacscripts do not use this property. Fallback value is that of `name`'
        maintainer:
          type: string
          example: 'John Doe <john.doe@pacstall.dev>'
        description:
          type: string
          example: 'Helper application for Linux distributions.'
        url:
          type: string
          example: 'https://sources.example.com/node/16.0.1/installer.deb'
        runtimeDependencies:
          type: array
          example: ["python3", "libx11-dev"]
          items:
            type: string
        buildDependencies:
          type: array
          example: ["python3", "libx11-dev"]
          items:
            type: string
        optionalDependencies:
          type: array
          example: ["xjadeo: video monitoring", "harvid: video timeline", "haskell"]
          description: 'Format: `$dependencyName[: $description]`'
          items:
            type: string
        breaks:
          type: array
          example: ["nodejs", "nodejs-bin", "nodejs-app", "nodejs-git"]
          items:
            type: string
        gives:
          type: string
          example: 'nodejs'
        replace:
          type: array
          example: 'nodejs-rust'
          items:
            type: string
        hash:
          type: string
          example: '5c7c0259062b9d4911d2537bfceaff5316f9de111698840a90d7cd497df891a6'
          description: 'Is empty string `""` if the package is a `git` type'
        ppa:
          type: array
          items:
            type: string
          example: ['dr-akulavich/lighttable']
        pacstallDependencies:
          type: array
          items:
            type: string
          example: ['alacritty']
        patch:
          type: array
          items:
            type: string
        repology:
          type: array
          items:
            type: string
        requiredBy:
          type: array
          items:
            type: string
          example: ['electron-deb']
        updateStatus:
          type: integer
          description: |
            `-1`: Unknown
            
            `0`: Latest
            
            `1`: Patch available
            
            `2`: Minor version available
            
            `3`: Major version available
          enum:
            - -1
            - 0
            - 1
            - 2
            - 3
          
    RepologyPackage:
      type: object
      properties:
        name:
          type: string
          example: 'nodejs-lts-deb'
        visibleName:
          type: string
          example: 'Node.js LTS'
        version:
          type: string
          example: '16.0.1'
        maintainer:
          type: object
          properties:
            name:
              type: string
              example: 'John Doe'
            email:
              type: string
              nullable: true
              example: 'john.doe@pacstall.dev'
        description:
          type: string
          example: 'Helper application for Linux distributions.'
        url:
          type: string
          example: 'https://sources.example.com/node/16.0.1/installer.deb'
        recipeUrl:
          type: string
          example: 'https://raw.githubusercontent.com/pacstall/pacstall-programs/master/packages/nodejs-lts-deb/nodejs-lts-deb.pacscript'
        packageDetailsUrl:
          type: string
          example: 'https://pacstall.dev/packages/adapta-gtk-theme-git'
        type:
          type: string
          enum:
            - 'Source Code'
            - 'Debian Native'
            - 'AppImage'
            - 'Precompiled'
        patches:
          type: array
          items:
            type: string
