name: deploy
on:
  push:
    tags:
      - '*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Node
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.17.6'

    - name: Install make
      run: sudo apt install make

    - name: Build Sources
      run: make

    - name: Publish new release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "webpacd.tar.gz"
        token: ${{ secrets.GITHUB_TOKEN }}